import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Menu } from "react-feather";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="pl-5 pr-3 lg:px-12 py-4 flex justify-between items-center">
          <img src="/images/gdsc-logo.png" className="lg:w-1/5 w-[66%]" />
          <div className="gap-x-8 lg:flex hidden">
            <a>About GDSC</a>
            <a>Events</a>
            <a>Resources</a>
            <a>More</a>
          </div>
          <button className="bg-[#5383EC] text-sm lg:text-base font-normal py-2 px-5 rounded-lg text-white">
            Join
          </button>
          <Menu className="lg:hidden" />
        </nav>
        {children}
      </body>
    </html>
  );
}
